course = 'mooc-programming-22'
[exercises.part03-01_print_numbers]
id = 152027
checksum = 'd98984a998bf85093b5952954fc4d6fa'

[exercises.part03-02_countdown]
id = 152052
checksum = 'a14726951e5a5b5437aef6a9d83ddcd9'

[exercises.part03-03_numbers]
id = 152038
checksum = 'b692d9ced0820a33531141e7c61e5d3d'

[exercises.part03-04_powers_of_two]
id = 152039
checksum = '452bd5d7fef49f78778f6bb6b7352a56'

[exercises.part03-05_powers_of_base_n]
id = 152028
checksum = '5721b182123283d394cb7846822228c5'

[exercises.part03-06_consecutive_sum_v1]
id = 152044
checksum = '2cc4221d9b7158d27a42aa04e8877a35'

[exercises.part03-07_consecutive_sum_v2]
id = 152032
checksum = 'e0cce1507ab1686836451231ee5a239f'

[exercises.part03-08_string_multiplied]
id = 152049
checksum = '50b33164b5ab2df3e22c819a155edb3e'

[exercises.part03-09_longer_string]
id = 152037
checksum = '37c8c137354dc9545c9930251475ffb6'

[exercises.part03-10_end_to_beginning]
id = 152055
checksum = 'e6c6ffbea3902d9f067c8298761eae72'

[exercises.part03-11_second_and_second_to_last]
id = 152025
checksum = '62e85926c12571826332758fbdc47b06'

[exercises.part03-12_line_of_hashes]
id = 152030
checksum = 'f640c0306981670c079bb70f1e2b6c42'

[exercises.part03-13_rectangle_of_hashes]
id = 152035
checksum = '648254f7e88c6e22c99985f6dd1d88c0'

[exercises.part03-14_underlining]
id = 152040
checksum = 'aae1085c06cbd108f5d7229169aa5a80'

[exercises.part03-15_right_aligned]
id = 152053
checksum = '1bcd4047d6892830e70500f6f0068105'

[exercises.part03-16_framed_word]
id = 152046
checksum = '0312e78cbe22da18a265d036778f0478'

[exercises.part03-17_substrings_part_1]
id = 152054
checksum = '37d11e2ef6dd779dd1c3849c0598369f'

[exercises.part03-18_substrings_part_2]
id = 152041
checksum = '035802cb85e5072aa1775bbca4610d0f'

[exercises.part03-19_does_it_contain_vowels]
id = 152029
checksum = '3c9c2ab5c5c74fcb325d86a220fac85b'

[exercises.part03-20_find_first_substring]
id = 152036
checksum = 'e080db0c13e68c6c9e2c5565dfbcb59e'

[exercises.part03-21_find_all_substrings]
id = 152023
checksum = 'd4de6bf81155679d8559dc0579d48fa7'

[exercises.part03-22_second_occurrence]
id = 152034
checksum = '9ecdf70727fc1dfe5d691b95f9bf6a68'

[exercises.part03-23_multiplication]
id = 152050
checksum = '4fe8ee70d8834d9bd69311380d442200'

[exercises.part03-24_first_letters_of_words]
id = 152045
checksum = '1377974641d7f126930f281da3b9e95e'

[exercises.part03-25_factorial]
id = 152043
checksum = '0728831a1538771c1c32521345d23a06'

[exercises.part03-26_flip_the_pairs]
id = 152026
checksum = '41025258a740bcc638d7ff3a02e58934'

[exercises.part03-27_taking_turns]
id = 152033
checksum = 'a65c4d123e743d01201a28be50672032'

[exercises.part03-28_seven_brothers]
id = 152047
checksum = 'c9e278653ee4f158420ac27589595150'

[exercises.part03-29_first_character]
id = 152051
checksum = 'b5d71c0e3cd31acd902bb226fc372b4f'

[exercises.part03-30_mean]
id = 152048
checksum = '8367381f5f691f173d48ff1b209bee44'

[exercises.part03-31_print_many_times]
id = 152031
checksum = 'c48820256528844649224c392fcf4fcc'

[exercises.part03-32_square_of_hashes]
id = 152024
checksum = '0e7f019ba79da32f68ee36b5f06e7ee5'

[exercises.part03-33_chessboard]
id = 152022
checksum = '7675d4aaca464acc660e4238db6d4ea6'

[exercises.part03-34_word_squared]
id = 152042
checksum = '0e6a2ffcf604f2f71c1f64e5a1842317'
